  nagios:
    image: jasonrivers/nagios:latest
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./etc:/opt/nagios/etc/
      - ./var:/opt/nagios/var/
      - ./plugins:/opt/Custom-Nagios-Plugins
      - ./nagiosgraph-var:/opt/nagiosgraph/var
      - ./nagiosgraph-etc:/opt/nagiosgraph/etc
